export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';


export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';