# Generated by Django 4.1.3 on 2023-05-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_shippingaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='addressName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
