# Generated by Django 4.1.3 on 2023-05-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_shippingaddress_addressname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='current_address',
            field=models.BooleanField(default=True),
        ),
    ]
